version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  pgsql:
    image: postgres:10.0
    ports:
     - "${MYSQL_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - vesselpgsql:/var/lib/postgresql/data
    networks:
     - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselpgsql:
    driver: "local"
  vesselredis:
    driver: "local"
